import sqlite3
import datetime
from datetime import timedelta

con = sqlite3.connect("Habit.db")
cur = con.cursor()

currentDate = datetime.date.today()

# In case of rerun this programme after the installation, remove the #:
#cur.execute("DROP Table Habits")
#cur.execute("DROP Table User")
#cur.execute("CREATE TABLE Habits(ID PRIMARY KEY, Date TIMESTAMP, User, Name, Period, Status, DateFinishTask TIMESTAMP, CreationDate TIMESTAMP, Streak, Active)")
#cur.execute("CREATE TABLE User(User, FirstName, LastName, EMail, Password, CreationDate TIMESTAMP)")

# Insert Dummy-Values in the habits-table:
data = [
(1, currentDate - timedelta(days=34), "Andi", "Eat Apple", "Daily", "Done", currentDate - timedelta(days=34), currentDate - timedelta(days=34), 1, "Active"),
(2, currentDate - timedelta(days=34), "Andi", "Sport", "Daily", "Done", currentDate - timedelta(days=34), currentDate - timedelta(days=34), 1, "Active"),
(3, currentDate - timedelta(days=34), "Andi", "Visit Parents", "Weekly", "Open", currentDate - timedelta(days=27), currentDate - timedelta(days=34), 0, "Active"),
(4, currentDate - timedelta(days=34), "Magi", "Sport", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(5, currentDate - timedelta(days=34), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(6, currentDate - timedelta(days=33), "Andi", "Eat Apple", "Daily", "Done", currentDate - timedelta(days=33), currentDate - timedelta(days=34), 2, "Active"),
(7, currentDate - timedelta(days=33), "Andi", "Sport", "Daily", "Failed", currentDate - timedelta(days=33), currentDate - timedelta(days=34), 0, "Active"),
(8, currentDate - timedelta(days=33), "Andi", "Visit Parents", "Weekly", "Open", currentDate - timedelta(days=27), currentDate - timedelta(days=34), 0, "Active"),
(9, currentDate - timedelta(days=33), "Magi", "Sport", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(10, currentDate - timedelta(days=33), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(11, currentDate - timedelta(days=32), "Andi", "Eat Apple", "Daily", "Done", currentDate - timedelta(days=32), currentDate - timedelta(days=34), 3, "Active"),
(12, currentDate - timedelta(days=32), "Andi", "Sport", "Daily", "Done", currentDate - timedelta(days=32), currentDate - timedelta(days=34), 1, "Active"),
(13, currentDate - timedelta(days=32), "Andi", "Visit Parents", "Weekly", "Open", currentDate - timedelta(days=27), currentDate - timedelta(days=34), 0, "Active"),
(14, currentDate - timedelta(days=32), "Magi", "Sport", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(15, currentDate - timedelta(days=32), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(16, currentDate - timedelta(days=31), "Andi", "Eat Apple", "Daily", "Done", currentDate - timedelta(days=31), currentDate - timedelta(days=34), 4, "Active"),
(17, currentDate - timedelta(days=31), "Andi", "Sport", "Daily", "Done", currentDate - timedelta(days=31), currentDate - timedelta(days=34), 2, "Active"),
(18, currentDate - timedelta(days=31), "Andi", "Visit Parents", "Weekly", "Done", currentDate - timedelta(days=27), currentDate - timedelta(days=34), 1, "Active"),
(19, currentDate - timedelta(days=31), "Magi", "Sport", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(20, currentDate - timedelta(days=31), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(21, currentDate - timedelta(days=30), "Andi", "Eat Apple", "Daily", "Failed", currentDate - timedelta(days=30), currentDate - timedelta(days=34), 0, "Active"),
(22, currentDate - timedelta(days=30), "Andi", "Sport", "Daily", "Failed", currentDate - timedelta(days=30), currentDate - timedelta(days=34), 0, "Active"),
(23, currentDate - timedelta(days=30), "Andi", "Visit Parents", "Weekly", "Done", currentDate - timedelta(days=27), currentDate - timedelta(days=34), 1, "Active"),
(24, currentDate - timedelta(days=30), "Magi", "Sport", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(25, currentDate - timedelta(days=30), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(26, currentDate - timedelta(days=29), "Andi", "Eat Apple", "Daily", "Done", currentDate - timedelta(days=29), currentDate - timedelta(days=34), 1, "Active"),
(27, currentDate - timedelta(days=29), "Andi", "Sport", "Daily", "Done", currentDate - timedelta(days=29), currentDate - timedelta(days=34), 1, "Active"),
(28, currentDate - timedelta(days=29), "Andi", "Visit Parents", "Weekly", "Done", currentDate - timedelta(days=27), currentDate - timedelta(days=34), 1, "Active"),
(29, currentDate - timedelta(days=29), "Magi", "Sport", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(30, currentDate - timedelta(days=29), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(31, currentDate - timedelta(days=28), "Andi", "Eat Apple", "Daily", "Failed", currentDate - timedelta(days=28), currentDate - timedelta(days=34), 0, "Active"),
(32, currentDate - timedelta(days=28), "Andi", "Sport", "Daily", "Failed", currentDate - timedelta(days=28), currentDate - timedelta(days=34), 0, "Active"),
(33, currentDate - timedelta(days=28), "Andi", "Visit Parents", "Weekly", "Done", currentDate - timedelta(days=27), currentDate - timedelta(days=34), 1, "Active"),
(34, currentDate - timedelta(days=28), "Magi", "Sport", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(35, currentDate - timedelta(days=28), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(36, currentDate - timedelta(days=27), "Andi", "Eat Apple", "Daily", "Failed", currentDate - timedelta(days=27), currentDate - timedelta(days=34), 0, "Active"),
(37, currentDate - timedelta(days=27), "Andi", "Sport", "Daily", "Failed", currentDate - timedelta(days=27), currentDate - timedelta(days=34), 0, "Active"),
(38, currentDate - timedelta(days=27), "Andi", "Visit Parents", "Weekly", "Done", currentDate - timedelta(days=27), currentDate - timedelta(days=34), 1, "Active"),
(39, currentDate - timedelta(days=27), "Magi", "Sport", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(40, currentDate - timedelta(days=27), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(41, currentDate - timedelta(days=26), "Andi", "Eat Apple", "Daily", "Done", currentDate - timedelta(days=26), currentDate - timedelta(days=34), 1, "Active"),
(42, currentDate - timedelta(days=26), "Andi", "Sport", "Daily", "Done", currentDate - timedelta(days=26), currentDate - timedelta(days=34), 1, "Active"),
(43, currentDate - timedelta(days=26), "Andi", "Visit Parents", "Weekly", "Open", currentDate - timedelta(days=20), currentDate - timedelta(days=34), 1, "Active"),
(44, currentDate - timedelta(days=26), "Magi", "Sport", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(45, currentDate - timedelta(days=26), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(46, currentDate - timedelta(days=25), "Andi", "Eat Apple", "Daily", "Done", currentDate - timedelta(days=25), currentDate - timedelta(days=34), 2, "Active"),
(47, currentDate - timedelta(days=25), "Andi", "Sport", "Daily", "Failed", currentDate - timedelta(days=25), currentDate - timedelta(days=34), 0, "Active"),
(48, currentDate - timedelta(days=25), "Andi", "Visit Parents", "Weekly", "Open", currentDate - timedelta(days=20), currentDate - timedelta(days=34), 1, "Active"),
(49, currentDate - timedelta(days=25), "Magi", "Sport", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(50, currentDate - timedelta(days=25), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(51, currentDate - timedelta(days=24), "Andi", "Eat Apple", "Daily", "Done", currentDate - timedelta(days=24), currentDate - timedelta(days=34), 3, "Active"),
(52, currentDate - timedelta(days=24), "Andi", "Sport", "Daily", "Done", currentDate - timedelta(days=24), currentDate - timedelta(days=34), 1, "Active"),
(53, currentDate - timedelta(days=24), "Andi", "Visit Parents", "Weekly", "Open", currentDate - timedelta(days=20), currentDate - timedelta(days=34), 1, "Active"),
(54, currentDate - timedelta(days=24), "Magi", "Sport", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(55, currentDate - timedelta(days=24), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(56, currentDate - timedelta(days=23), "Andi", "Eat Apple", "Daily", "Done", currentDate - timedelta(days=23), currentDate - timedelta(days=34), 4, "Active"),
(57, currentDate - timedelta(days=23), "Andi", "Sport", "Daily", "Done", currentDate - timedelta(days=23), currentDate - timedelta(days=34), 2, "Active"),
(58, currentDate - timedelta(days=23), "Andi", "Visit Parents", "Weekly", "Open", currentDate - timedelta(days=20), currentDate - timedelta(days=34), 1, "Active"),
(59, currentDate - timedelta(days=23), "Magi", "Sport", "Monthly", "Done", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 1, "Active"),
(60, currentDate - timedelta(days=23), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(61, currentDate - timedelta(days=22), "Andi", "Eat Apple", "Daily", "Done", currentDate - timedelta(days=22), currentDate - timedelta(days=34), 5, "Active"),
(62, currentDate - timedelta(days=22), "Andi", "Sport", "Daily", "Done", currentDate - timedelta(days=22), currentDate - timedelta(days=34), 3, "Active"),
(63, currentDate - timedelta(days=22), "Andi", "Visit Parents", "Weekly", "Open", currentDate - timedelta(days=20), currentDate - timedelta(days=34), 1, "Active"),
(64, currentDate - timedelta(days=22), "Magi", "Sport", "Monthly", "Done", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 1, "Active"),
(65, currentDate - timedelta(days=22), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(66, currentDate - timedelta(days=21), "Andi", "Eat Apple", "Daily", "Done", currentDate - timedelta(days=21), currentDate - timedelta(days=34), 6, "Active"),
(67, currentDate - timedelta(days=21), "Andi", "Sport", "Daily", "Failed", currentDate - timedelta(days=21), currentDate - timedelta(days=34), 0, "Active"),
(68, currentDate - timedelta(days=21), "Andi", "Visit Parents", "Weekly", "Open", currentDate - timedelta(days=20), currentDate - timedelta(days=34), 1, "Active"),
(69, currentDate - timedelta(days=21), "Magi", "Sport", "Monthly", "Done", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 1, "Active"),
(70, currentDate - timedelta(days=21), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(71, currentDate - timedelta(days=20), "Andi", "Eat Apple", "Daily", "Done", currentDate - timedelta(days=20), currentDate - timedelta(days=34), 7, "Active"),
(72, currentDate - timedelta(days=20), "Andi", "Sport", "Daily", "Done", currentDate - timedelta(days=20), currentDate - timedelta(days=34), 1, "Active"),
(73, currentDate - timedelta(days=20), "Andi", "Visit Parents", "Weekly", "Done", currentDate - timedelta(days=20), currentDate - timedelta(days=34), 2, "Active"),
(74, currentDate - timedelta(days=20), "Magi", "Sport", "Monthly", "Done", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 1, "Active"),
(75, currentDate - timedelta(days=20), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(76, currentDate - timedelta(days=19), "Andi", "Eat Apple", "Daily", "Done", currentDate - timedelta(days=19), currentDate - timedelta(days=34), 8, "Active"),
(77, currentDate - timedelta(days=19), "Andi", "Sport", "Daily", "Done", currentDate - timedelta(days=19), currentDate - timedelta(days=34), 2, "Active"),
(78, currentDate - timedelta(days=19), "Andi", "Visit Parents", "Weekly", "Open", currentDate - timedelta(days=13), currentDate - timedelta(days=34), 2, "Active"),
(79, currentDate - timedelta(days=19), "Magi", "Sport", "Monthly", "Done", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 1, "Active"),
(80, currentDate - timedelta(days=19), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(81, currentDate - timedelta(days=18), "Andi", "Eat Apple", "Daily", "Failed", currentDate - timedelta(days=18), currentDate - timedelta(days=34), 0, "Active"),
(82, currentDate - timedelta(days=18), "Andi", "Sport", "Daily", "Failed", currentDate - timedelta(days=18), currentDate - timedelta(days=34), 0, "Active"),
(83, currentDate - timedelta(days=18), "Andi", "Visit Parents", "Weekly", "Open", currentDate - timedelta(days=13), currentDate - timedelta(days=34), 2, "Active"),
(84, currentDate - timedelta(days=18), "Magi", "Sport", "Monthly", "Done", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 1, "Active"),
(85, currentDate - timedelta(days=18), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(86, currentDate - timedelta(days=17), "Andi", "Eat Apple", "Daily", "Failed", currentDate - timedelta(days=17), currentDate - timedelta(days=34), 0, "Active"),
(87, currentDate - timedelta(days=17), "Andi", "Sport", "Daily", "Failed", currentDate - timedelta(days=17), currentDate - timedelta(days=34), 0, "Active"),
(88, currentDate - timedelta(days=17), "Andi", "Visit Parents", "Weekly", "Open", currentDate - timedelta(days=13), currentDate - timedelta(days=34), 2, "Active"),
(89, currentDate - timedelta(days=17), "Magi", "Sport", "Monthly", "Done", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 1, "Active"),
(90, currentDate - timedelta(days=17), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(91, currentDate - timedelta(days=16), "Andi", "Eat Apple", "Daily", "Failed", currentDate - timedelta(days=16), currentDate - timedelta(days=34), 0, "Active"),
(92, currentDate - timedelta(days=16), "Andi", "Sport", "Daily", "Failed", currentDate - timedelta(days=16), currentDate - timedelta(days=34), 0, "Active"),
(93, currentDate - timedelta(days=16), "Andi", "Visit Parents", "Weekly", "Open", currentDate - timedelta(days=13), currentDate - timedelta(days=34), 2, "Active"),
(94, currentDate - timedelta(days=16), "Magi", "Sport", "Monthly", "Done", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 1, "Active"),
(95, currentDate - timedelta(days=16), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(96, currentDate - timedelta(days=15), "Andi", "Eat Apple", "Daily", "Failed", currentDate - timedelta(days=15), currentDate - timedelta(days=34), 0, "Active"),
(97, currentDate - timedelta(days=15), "Andi", "Sport", "Daily", "Failed", currentDate - timedelta(days=15), currentDate - timedelta(days=34), 0, "Active"),
(98, currentDate - timedelta(days=15), "Andi", "Visit Parents", "Weekly", "Open", currentDate - timedelta(days=13), currentDate - timedelta(days=34), 2, "Active"),
(99, currentDate - timedelta(days=15), "Magi", "Sport", "Monthly", "Done", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 1, "Active"),
(100, currentDate - timedelta(days=15), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(101, currentDate - timedelta(days=14), "Andi", "Eat Apple", "Daily", "Failed", currentDate - timedelta(days=14), currentDate - timedelta(days=34), 0, "Active"),
(102, currentDate - timedelta(days=14), "Andi", "Sport", "Daily", "Failed", currentDate - timedelta(days=14), currentDate - timedelta(days=34), 0, "Active"),
(103, currentDate - timedelta(days=14), "Andi", "Visit Parents", "Weekly", "Open", currentDate - timedelta(days=13), currentDate - timedelta(days=34), 2, "Active"),
(104, currentDate - timedelta(days=14), "Magi", "Sport", "Monthly", "Done", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 1, "Active"),
(105, currentDate - timedelta(days=14), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(106, currentDate - timedelta(days=13), "Andi", "Eat Apple", "Daily", "Done", currentDate - timedelta(days=13), currentDate - timedelta(days=34), 1, "Active"),
(107, currentDate - timedelta(days=13), "Andi", "Sport", "Daily", "Done", currentDate - timedelta(days=13), currentDate - timedelta(days=34), 1, "Active"),
(108, currentDate - timedelta(days=13), "Andi", "Visit Parents", "Weekly", "Failed", currentDate - timedelta(days=13), currentDate - timedelta(days=34), 0, "Active"),
(109, currentDate - timedelta(days=13), "Magi", "Sport", "Monthly", "Done", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 1, "Active"),
(110, currentDate - timedelta(days=13), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(111, currentDate - timedelta(days=12), "Andi", "Eat Apple", "Daily", "Done", currentDate - timedelta(days=12), currentDate - timedelta(days=34), 2, "Active"),
(112, currentDate - timedelta(days=12), "Andi", "Sport", "Daily", "Failed", currentDate - timedelta(days=12), currentDate - timedelta(days=34), 0, "Active"),
(113, currentDate - timedelta(days=12), "Andi", "Visit Parents", "Weekly", "Open", currentDate - timedelta(days=6), currentDate - timedelta(days=34), 0, "Active"),
(114, currentDate - timedelta(days=12), "Magi", "Sport", "Monthly", "Done", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 1, "Active"),
(115, currentDate - timedelta(days=12), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(116, currentDate - timedelta(days=11), "Andi", "Eat Apple", "Daily", "Failed", currentDate - timedelta(days=11), currentDate - timedelta(days=34), 0, "Active"),
(117, currentDate - timedelta(days=11), "Andi", "Sport", "Daily", "Failed", currentDate - timedelta(days=11), currentDate - timedelta(days=34), 0, "Active"),
(118, currentDate - timedelta(days=11), "Andi", "Visit Parents", "Weekly", "Done", currentDate - timedelta(days=6), currentDate - timedelta(days=34), 1, "Active"),
(119, currentDate - timedelta(days=11), "Magi", "Sport", "Monthly", "Done", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 1, "Active"),
(120, currentDate - timedelta(days=11), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(121, currentDate - timedelta(days=10), "Andi", "Eat Apple", "Daily", "Done", currentDate - timedelta(days=10), currentDate - timedelta(days=34), 1, "Active"),
(122, currentDate - timedelta(days=10), "Andi", "Sport", "Daily", "Done", currentDate - timedelta(days=10), currentDate - timedelta(days=34), 1, "Active"),
(123, currentDate - timedelta(days=10), "Andi", "Visit Parents", "Weekly", "Done", currentDate - timedelta(days=6), currentDate - timedelta(days=34), 1, "Active"),
(124, currentDate - timedelta(days=10), "Magi", "Sport", "Monthly", "Done", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 1, "Active"),
(125, currentDate - timedelta(days=10), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(126, currentDate - timedelta(days=9), "Andi", "Eat Apple", "Daily", "Failed", currentDate - timedelta(days=9), currentDate - timedelta(days=34), 0, "Active"),
(127, currentDate - timedelta(days=9), "Andi", "Sport", "Daily", "Done", currentDate - timedelta(days=9), currentDate - timedelta(days=34), 2, "Active"),
(128, currentDate - timedelta(days=9), "Andi", "Visit Parents", "Weekly", "Done", currentDate - timedelta(days=6), currentDate - timedelta(days=34), 1, "Active"),
(129, currentDate - timedelta(days=9), "Magi", "Sport", "Monthly", "Done", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 1, "Active"),
(130, currentDate - timedelta(days=9), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(131, currentDate - timedelta(days=8), "Andi", "Eat Apple", "Daily", "Done", currentDate - timedelta(days=8), currentDate - timedelta(days=34), 1, "Active"),
(132, currentDate - timedelta(days=8), "Andi", "Sport", "Daily", "Failed", currentDate - timedelta(days=8), currentDate - timedelta(days=34), 0, "Active"),
(133, currentDate - timedelta(days=8), "Andi", "Visit Parents", "Weekly", "Done", currentDate - timedelta(days=6), currentDate - timedelta(days=34), 1, "Active"),
(134, currentDate - timedelta(days=8), "Magi", "Sport", "Monthly", "Done", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 1, "Active"),
(135, currentDate - timedelta(days=8), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(136, currentDate - timedelta(days=7), "Andi", "Eat Apple", "Daily", "Done", currentDate - timedelta(days=7), currentDate - timedelta(days=34), 2, "Active"),
(137, currentDate - timedelta(days=7), "Andi", "Sport", "Daily", "Done", currentDate - timedelta(days=7), currentDate - timedelta(days=34), 2, "Active"),
(138, currentDate - timedelta(days=7), "Andi", "Visit Parents", "Weekly", "Done", currentDate - timedelta(days=6), currentDate - timedelta(days=34), 1, "Active"),
(139, currentDate - timedelta(days=7), "Magi", "Sport", "Monthly", "Done", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 1, "Active"),
(140, currentDate - timedelta(days=7), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(141, currentDate - timedelta(days=6), "Andi", "Eat Apple", "Daily", "Done", currentDate - timedelta(days=6), currentDate - timedelta(days=34), 3, "Active"),
(142, currentDate - timedelta(days=6), "Andi", "Sport", "Daily", "Done", currentDate - timedelta(days=6), currentDate - timedelta(days=34), 3, "Active"),
(143, currentDate - timedelta(days=6), "Andi", "Visit Parents", "Weekly", "Done", currentDate - timedelta(days=6), currentDate - timedelta(days=34), 1, "Active"),
(144, currentDate - timedelta(days=6), "Magi", "Sport", "Monthly", "Done", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 1, "Active"),
(145, currentDate - timedelta(days=6), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(146, currentDate - timedelta(days=5), "Andi", "Eat Apple", "Daily", "Done", currentDate - timedelta(days=5), currentDate - timedelta(days=34), 4, "Active"),
(147, currentDate - timedelta(days=5), "Andi", "Sport", "Daily", "Done", currentDate - timedelta(days=5), currentDate - timedelta(days=34), 4, "Active"),
(148, currentDate - timedelta(days=5), "Andi", "Visit Parents", "Weekly", "Open", currentDate - timedelta(days=-1), currentDate - timedelta(days=34), 1, "Active"),
(149, currentDate - timedelta(days=5), "Magi", "Sport", "Monthly", "Done", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 1, "Active"),
(150, currentDate - timedelta(days=5), "Magi", "Read Book", "Monthly", "Open", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(151, currentDate - timedelta(days=4), "Andi", "Eat Apple", "Daily", "Done", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 5, "Active"),
(152, currentDate - timedelta(days=4), "Andi", "Sport", "Daily", "Done", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 5, "Active"),
(153, currentDate - timedelta(days=4), "Andi", "Visit Parents", "Weekly", "Open", currentDate - timedelta(days=-1), currentDate - timedelta(days=34), 1, "Active"),
(154, currentDate - timedelta(days=4), "Magi", "Sport", "Monthly", "Done", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 1, "Active"),
(155, currentDate - timedelta(days=4), "Magi", "Read Book", "Monthly", "Failed", currentDate - timedelta(days=4), currentDate - timedelta(days=34), 0, "Active"),
(156, currentDate - timedelta(days=3), "Andi", "Eat Apple", "Daily", "Failed", currentDate - timedelta(days=3), currentDate - timedelta(days=34), 0, "Active"),
(157, currentDate - timedelta(days=3), "Andi", "Sport", "Daily", "Failed", currentDate - timedelta(days=3), currentDate - timedelta(days=34), 0, "Active"),
(158, currentDate - timedelta(days=3), "Andi", "Visit Parents", "Weekly", "Open", currentDate - timedelta(days=-1), currentDate - timedelta(days=34), 1, "Active"),
(159, currentDate - timedelta(days=3), "Magi", "Sport", "Monthly", "Open", currentDate + timedelta(days=26), currentDate - timedelta(days=34), 1, "Active"),
(160, currentDate - timedelta(days=3), "Magi", "Read Book", "Monthly", "Open", currentDate + timedelta(days=26), currentDate - timedelta(days=34), 1, "Active"),
(161, currentDate - timedelta(days=2), "Andi", "Eat Apple", "Daily", "Done", currentDate - timedelta(days=2), currentDate - timedelta(days=34), 1, "Active"),
(162, currentDate - timedelta(days=2), "Andi", "Sport", "Daily", "Failed", currentDate - timedelta(days=2), currentDate - timedelta(days=34), 0, "Active"),
(163, currentDate - timedelta(days=2), "Andi", "Visit Parents", "Weekly", "Open", currentDate - timedelta(days=-1), currentDate - timedelta(days=34), 1, "Active"),
(164, currentDate - timedelta(days=2), "Magi", "Sport", "Monthly", "Open", currentDate + timedelta(days=26), currentDate - timedelta(days=34), 1, "Active"),
(165, currentDate - timedelta(days=2), "Magi", "Read Book", "Monthly", "Open", currentDate + timedelta(days=26), currentDate - timedelta(days=34), 1, "Inactive"),
(166, currentDate - timedelta(days=1), "Andi", "Eat Apple", "Daily", "Done", currentDate - timedelta(days=1), currentDate - timedelta(days=34), 2, "Active"),
(167, currentDate - timedelta(days=1), "Andi", "Sport", "Daily", "Done", currentDate - timedelta(days=1), currentDate - timedelta(days=34), 1, "Active"),
(168, currentDate - timedelta(days=1), "Andi", "Visit Parents", "Weekly", "Open", currentDate - timedelta(days=-1), currentDate - timedelta(days=34), 1, "Active"),
(169, currentDate - timedelta(days=1), "Magi", "Sport", "Monthly", "Open", currentDate + timedelta(days=26), currentDate - timedelta(days=34), 1, "Active"),
(170, currentDate - timedelta(days=0), "Andi", "Eat Apple", "Daily", "Open", currentDate - timedelta(days=0), currentDate - timedelta(days=34), 2, "Active"),
(171, currentDate - timedelta(days=0), "Andi", "Sport", "Daily", "Open", currentDate - timedelta(days=0), currentDate - timedelta(days=34), 1, "Active"),
(172, currentDate - timedelta(days=0), "Andi", "Visit Parents", "Weekly", "Open", currentDate - timedelta(days=-1), currentDate - timedelta(days=34), 1, "Active"),
(173, currentDate - timedelta(days=0), "Magi", "Sport", "Monthly", "Open", currentDate + timedelta(days=26), currentDate - timedelta(days=34), 1, "Active"),

]
cur.executemany("INSERT INTO Habits VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", data)
con.commit()

# Inserts Dummy-Users in the habits-table:
user = [
    ("admin", "Admin", "Admin", "", "PW1234!", '2023-03-01'),
    ("Andi", "Andreas", "Pflügl", "andi.pfluegl@gmail.com", "", '2023-03-01'),
    ("Magi", "Magdalena", "Test", "magi.test@gmx.at", "", '2023-03-01'),
]

cur.executemany("INSERT INTO User VALUES(?, ?, ?, ?, ?, ?)", user)
con.commit()

con.close()